version: 2
jobs:
  linux:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: INSTALL DEPENDENCIES
          command: apt-get -y update;
            apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev wget;
            apt-get install -y software-properties-common;
            apt-get install -y libminiupnpc-dev libzmq3-dev;
            apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev
      - run:
          name: LIBDB
          command: apt-get install -y checkinstall;
            wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz;
            tar -xzvf db-4.8.30.NC.tar.gz;
            cd db-4.8.30.NC/build_unix;
            ../dist/configure --enable-cxx --prefix=/usr;
            make;
            checkinstall --fstrans=no --pkgversion=4.8.30 --pkgname=libdb-dev --nodoc -y
      - run:
          name: AUTOGEN
          command: ./autogen.sh
      - run:
          name: CONFIGURE
          command: ./configure
      - run:
          name: BUILD Jemcash
          command: make -j2
      - run:
          name: RUN Unit test
          command: make check
  windows:
      docker:
        - image: ubuntu:latest
      steps:
        - checkout
        - run:
            name: INSTALL DEPENDENCIES
            command: apt-get -y update;
              apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev wget;
              apt-get install -y software-properties-common;
              apt-get install -y libminiupnpc-dev libzmq3-dev;
              apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev;
              apt-get install -y g++-mingw-w64-i686 mingw-w64-i686-dev g++-mingw-w64-x86-64 mingw-w64-x86-64-dev curl
        - run:
            name: LIBDB
            command: apt-get install -y checkinstall;
              wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz;
              tar -xzvf db-4.8.30.NC.tar.gz;
              cd db-4.8.30.NC/build_unix;
              ../dist/configure --enable-cxx --prefix=/usr;
              make -j2;
              checkinstall --fstrans=no --pkgversion=4.8.30 --pkgname=libdb-dev --nodoc -y
        - run:
            name: CHANGE DIR DEPENDS
            command: make -C depends HOST=x86_64-w64-mingw32
        - run:
            name: CONFIGURE Windows
            command: echo $(pwd);
              ./autogen.sh;
              ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32
        - run:
            name: BUILD Jemcash Windows
            command: make -j2
workflows:
  version: 2
  linux_and_windows:
    jobs:
      - linux
      - windows
